id: I026F49D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:31:57+00:00'
last_modified: '2022-06-08T12:41:46.465474+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5357
  title: བྱ་སྤྲེལ་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B66B:
      image_group_id: I3CN5359
      title: ''
      total_pages: 54
      order: 1
      base_file: B66B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
