id: P010316
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5357
  title: བྱ་སྤྲེལ་གཏམ་རྒྱུད།
  author: ''
  volumes:
    d22fe490a1bd42249562def4a220ff47:
      image_group_id: I3CN5359
      title: ''
      volume_number: 1
      total_pages: 54
