id: P010316
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:43:43.035323
source_metadata:
  id: bdr:W3CN5357
  title: བྱ་སྤྲེལ་གཏམ་རྒྱུད།
  author: ''
  volumes:
    d22fe490a1bd42249562def4a220ff47:
      image_group_id: I3CN5359
      title: ''
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
